
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acmknwxnyibvbbltfdxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjbWtud3hueWlidmJibHRmZHhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczOTc2NDIsImV4cCI6MjA1Mjk3MzY0Mn0.StIEGX1joj7gESXTn5jdtFNvDBMmvDKILchNr_BYUHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Extend the Database type to include the partnership_requests table
type ExtendedDatabase = Database & {
  public: {
    Tables: {
      partnership_requests: {
        Row: {
          id: string;
          created_at: string;
          name: string;
          email: string;
          phone: string;
          city: string;
          experience: string;
          message: string | null;
          profile_type: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          name: string;
          email: string;
          phone: string;
          city: string;
          experience: string;
          message?: string | null;
          profile_type?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          name?: string;
          email?: string;
          phone?: string;
          city?: string;
          experience?: string;
          message?: string | null;
          profile_type?: string | null;
        };
      } & Database["public"]["Tables"]
    } & Database["public"]["Views"]
  }
};

export const supabase = createClient<ExtendedDatabase>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true
    }
  }
);
